SYMBOL_MAP = {
    "Bullseye": "Bullseye",
    "one": "One",
    "two": "Two",
    "three": "Three",
    "four": "Four",
    "five": "Five",
    "six": "Six",
    "seven": "Seven",
    "eight": "Eight",
    "nine": "Nine",
    "A": "A",
    "B": "B",
    "C": "C",
    "D": "D",
    "E": "E",
    "F": "F",
    "G": "G",
    "H": "H",
    "S": "S",
    "T": "T",
    "U": "U",
    "V": "V",
    "W": "W",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    "up": "Up Arrow",
    "down": "Down Arrow",
    "Right": "Right Arrow",
    "Left": "Left Arrow",
    "circle": "Stop"
}
